import { promises as fs } from "node:fs";
import path from "node:path";

type IconEntry = {
	body: string;
	width: number;
	height: number;
};

type IconPack = {
	prefix: string;
	icons: Record<string, IconEntry>;
};

type RawManifest = {
	fetchedAt: string;
	fabricCount: number;
	azureCount: number;
	fabricSource: string;
	azureSource: string;
};

const ROOT_DIR = path.resolve(__dirname, "..");
const RAW_DIR = path.join(ROOT_DIR, "raw");
const DIST_DIR = path.join(ROOT_DIR, "dist");
const DOCS_CATALOGUE_PATH = path.join(ROOT_DIR, "docs", "icon-catalogue.md");
const COPILOT_INSTRUCTIONS_PATH = path.join(ROOT_DIR, ".github", "copilot-instructions.md");
const STATUS_PATH = path.join(ROOT_DIR, "STATUS.md");

async function readJsonFile<T>(filePath: string): Promise<T> {
	const raw = await fs.readFile(filePath, "utf8");
	return JSON.parse(raw) as T;
}

function getIconCount(pack: IconPack): number {
	return Object.keys(pack.icons).length;
}

function sortedEntries(pack: IconPack): Array<[string, IconEntry]> {
	return Object.entries(pack.icons).sort((a, b) => a[0].localeCompare(b[0]));
}

function generateIconCatalogue(fabric: IconPack, azure: IconPack, timestamp: string): string {
	const fabricRows = sortedEntries(fabric)
		.map(([slug, icon]) => `| ${slug} | ${icon.width} | ${icon.height} |`)
		.join("\n");
	const azureRows = sortedEntries(azure)
		.map(([slug, icon]) => `| ${slug} | ${icon.width} | ${icon.height} |`)
		.join("\n");

	return [
		"# Icon Catalogue",
		"",
		"Auto-generated by `npm run build:icons`. Do not edit manually.",
		`Last updated: ${timestamp}`,
		"",
		"## Fabric icons (prefix: `fabric`)",
		"",
		"| Slug | Width | Height |",
		"|------|-------|--------|",
		fabricRows,
		"",
		"## Azure icons (prefix: `azure`)",
		"",
		"| Slug | Width | Height |",
		"|------|-------|--------|",
		azureRows,
		"",
	].join("\n");
}

function prettifySlug(slug: string): string {
	return slug
		.split("-")
		.filter(Boolean)
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
		.join(" ");
}

function generateCopilotTable(pack: IconPack): string {
	const rows = sortedEntries(pack)
		.map(([slug]) => `| ${slug} | ${prettifySlug(slug)} |`)
		.join("\n");

	return ["| Slug | Service |", "|------|---------|", rows].join("\n");
}

function replaceSectionTable(
	content: string,
	heading: string,
	table: string,
	nextHeading?: string
): string {
	const start = content.indexOf(heading);
	if (start === -1) {
		throw new Error(`Unable to find heading: ${heading}`);
	}

	const headingEnd = start + heading.length;
	const sectionStart = content.indexOf("\n", headingEnd);
	if (sectionStart === -1) {
		throw new Error(`Unable to find section start after heading: ${heading}`);
	}

	let end = content.length;
	if (nextHeading) {
		const next = content.indexOf(nextHeading, sectionStart + 1);
		if (next !== -1) {
			end = next;
		}
	}

	const before = content.slice(0, sectionStart + 1);
	const after = content.slice(end);
	return `${before}\n${table}\n\n${after.replace(/^\s+/, "")}`;
}

async function updateCopilotInstructions(fabric: IconPack, azure: IconPack): Promise<void> {
	let content = await fs.readFile(COPILOT_INSTRUCTIONS_PATH, "utf8");
	content = replaceSectionTable(
		content,
		"## Fabric icon slugs (prefix: `fabric`)",
		generateCopilotTable(fabric),
		"## Azure icon slugs (prefix: `azure`)"
	);
	content = replaceSectionTable(content, "## Azure icon slugs (prefix: `azure`)", generateCopilotTable(azure), "## Current build state");
	await fs.writeFile(COPILOT_INSTRUCTIONS_PATH, content, "utf8");
}

async function updateStatus(fabricCount: number, azureCount: number): Promise<void> {
	let content = await fs.readFile(STATUS_PATH, "utf8");

	content = content.replace(
		/\| dist\/fabric\.json \| .*?\|.*?\|/,
		"| dist/fabric.json | ✅ Done | Phase 2 |"
	);
	content = content.replace(
		/\| dist\/azure\.json \| .*?\|.*?\|/,
		"| dist/azure.json | ✅ Done | Phase 2 |"
	);
	content = content.replace(/- Fabric icons: .*/, `- Fabric icons: ${fabricCount}`);
	content = content.replace(/- Azure icons: .*/, `- Azure icons: ${azureCount}`);
	content = content.replace(/## Last full build\n.*/m, `## Last full build\n${new Date().toISOString()}`);

	await fs.writeFile(STATUS_PATH, content, "utf8");
}

async function main(): Promise<void> {
	const fabricConvertedPath = path.join(RAW_DIR, "fabric-converted.json");
	const azureConvertedPath = path.join(RAW_DIR, "azure-converted.json");
	const rawManifestPath = path.join(RAW_DIR, "manifest.json");

	const fabric = await readJsonFile<IconPack>(fabricConvertedPath);
	const azure = await readJsonFile<IconPack>(azureConvertedPath);

	const fabricCount = getIconCount(fabric);
	const azureCount = getIconCount(azure);
	if (fabricCount < 10 || azureCount < 10) {
		throw new Error("Build validation failed: expected at least 10 icons in each pack");
	}

	await fs.mkdir(DIST_DIR, { recursive: true });
	await fs.writeFile(path.join(DIST_DIR, "fabric.json"), `${JSON.stringify(fabric, null, 2)}\n`, "utf8");
	await fs.writeFile(path.join(DIST_DIR, "azure.json"), `${JSON.stringify(azure, null, 2)}\n`, "utf8");

	const rawManifest = await readJsonFile<RawManifest>(rawManifestPath);
	const distManifest = {
		builtAt: new Date().toISOString(),
		fabricIconCount: fabricCount,
		azureIconCount: azureCount,
		fabricSource: rawManifest.fabricSource,
		azureSource: rawManifest.azureSource,
	};
	await fs.writeFile(path.join(DIST_DIR, "manifest.json"), `${JSON.stringify(distManifest, null, 2)}\n`, "utf8");

	const now = new Date().toISOString();
	await fs.writeFile(DOCS_CATALOGUE_PATH, generateIconCatalogue(fabric, azure, now), "utf8");
	await updateCopilotInstructions(fabric, azure);
	await updateStatus(fabricCount, azureCount);

	console.log(`Built dist/fabric.json (${fabricCount} icons)`);
	console.log(`Built dist/azure.json (${azureCount} icons)`);
}

main().catch((error: unknown) => {
	const message = error instanceof Error ? error.message : String(error);
	console.error(message);
	process.exit(1);
});
